title: Yanting Yang
author: Yanting Yang
email: yanting.yang@ece.ubc.ca
description: >
  This is Yanting Yang' site.

github_username: yanting-yang
rss: rss

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

markdown: GFM
